name: Upload to GCS
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP via WIF
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/578920165205/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@your-gcp-project-id.iam.gserviceaccount.com"

      - name: Upload file to GCS
        run: gsutil cp index.html gs://github-actions-read-write-bucket/
