name: List GCS Objects with WIF

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  id-token: write # Required for workload identity federation

jobs:
  list_objects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: List GCS objects
        run: |
          echo ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          echo ${{ secrets.GCP_SA_EMAIL }}
          echo ${{ secrets.GCS_BUCKET_NAME }}
          gcloud storage ls gs://${{ secrets.GCS_BUCKET_NAME }}
